project:
  type: website

website:
  page-navigation: true
  title: "ESTAT0016 - Tópicos Especiais em Estatística"
  description: "Página para ESTAT0016 - Tópicos Especiais em Estatística, UFS, 2023-2."
  site-url: "https://sta210-s22.github.io/website/"

  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Mine Çetinkaya-Rundel"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center

    style: "docked"
    search: true
    contents:
      - sobre.qmd
      - calendario.qmd
      - recursos.qmd
      - material.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual